# Generated by Django 6.0 on 2026-01-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='chat_theme',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
