# Generated by Django 6.0 on 2026-02-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_thread_chat_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reaction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='chat_theme',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
